# Generated by Django 5.2.4 on 2025-07-17 01:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FieldWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_employee_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "odoo_contract_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("identification_number", models.CharField(max_length=10, unique=True)),
                ("wage", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "contract_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["odoo_employee_id"],
                        name="payroll_fie_odoo_em_faced0_idx",
                    ),
                    models.Index(
                        fields=["odoo_contract_id"],
                        name="payroll_fie_odoo_co_f5ba23_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="payroll_fie_is_acti_8fd3a8_idx"
                    ),
                ],
            },
        ),
    ]
