# Generated by Django 5.2.4 on 2025-07-22 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_alter_fieldworker_wage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=8, unique=True)),
                ("calculates_integral", models.BooleanField(default=True)),
                ("calculates_thirteenth_bonus", models.BooleanField(default=True)),
                ("calculates_fourteenth_bonus", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Uom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActivityGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=8, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["code"], name="payroll_act_code_16ce52_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=8, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["code"], name="payroll_far_code_cbf2c4_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.activitygroup",
                    ),
                ),
                (
                    "labor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.labortype",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payroll.uom"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollBatchLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "salary_surplus",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "integral_bonus",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "mobilization_bonus",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "extra_hours_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "extra_hours_qty",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "thirteenth_bonus",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "fourteenth_bonus",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.activity",
                    ),
                ),
                (
                    "field_worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.fieldworker",
                    ),
                ),
                (
                    "payroll_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.payrollbatch",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["payroll_batch"], name="payroll_pay_payroll_da6d00_idx"
                    ),
                    models.Index(
                        fields=["field_worker"], name="payroll_pay_field_w_e14642_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payroll_batch", "field_worker", "activity"),
                        name="unique_payroll_batch_line",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_per_unit", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.activity",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payroll.farm"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity", "farm"), name="unique_activity_farm"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["activity_group"], name="payroll_act_activit_b94bb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["labor_type"], name="payroll_act_labor_t_c4e2bd_idx"
            ),
        ),
    ]
