# Generated by Django 5.2.4 on 2025-07-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_labortype_uom_activitygroup_farm_activity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobilization_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "extra_hours_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "basic_monthly_wage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
