# Generated by Django 5.2.4 on 2025-07-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0004_payrollconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="name",
            field=models.CharField(default="test", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activitygroup",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
