# Generated by Django 5.2.4 on 2025-07-28 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_alter_payrollbatch_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollbatch",
            name="farm",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="payroll.farm",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payrollbatch",
            name="iso_week",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="payrollbatch",
            name="iso_year",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="payrollbatchline",
            name="iso_week",
            field=models.PositiveSmallIntegerField(default=52, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payrollbatchline",
            name="iso_year",
            field=models.PositiveSmallIntegerField(default=2025, editable=False),
            preserve_default=False,
        ),
    ]
