# Generated by Django 5.2.4 on 2025-07-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0007_payrollbatch_farm_payrollbatch_iso_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollbatchline",
            name="extra_hours_qty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payrollbatchline",
            name="extra_hours_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payrollbatchline",
            name="fourteenth_bonus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payrollbatchline",
            name="integral_bonus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payrollbatchline",
            name="mobilization_bonus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payrollbatchline",
            name="salary_surplus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payrollbatchline",
            name="thirteenth_bonus",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payrollbatchline",
            name="total_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
