# Generated by Django 5.2.4 on 2025-07-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0009_payrollconfiguration_extra_hour_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollconfiguration",
            name="daily_payroll_line_worker_limit",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
