# Generated by Django 5.2.4 on 2025-07-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0010_payrollconfiguration_daily_payroll_line_worker_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollconfiguration",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
