# Generated by Django 5.2.4 on 2025-07-30 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0011_alter_payrollconfiguration_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payrollconfiguration",
            old_name="extra_hour_value",
            new_name="extra_hour_multiplier",
        ),
    ]
