# Generated by Django 5.2.4 on 2025-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payroll",
            "0012_rename_extra_hour_value_payrollconfiguration_extra_hour_multiplier",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payrollbatchline",
            name="unique_payroll_batch_line",
        ),
        migrations.AddConstraint(
            model_name="payrollbatchline",
            constraint=models.UniqueConstraint(
                fields=("field_worker", "activity", "date"),
                name="unique_payroll_batch_line",
            ),
        ),
    ]
