# Generated by Django 5.2.4 on 2025-07-30 21:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0013_remove_payrollbatchline_unique_payroll_batch_line_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollbatchline",
            name="extra_hours_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payrollbatchline",
            name="extra_hours_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payrollbatchline",
            name="fourteenth_bonus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payrollbatchline",
            name="integral_bonus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payrollbatchline",
            name="mobilization_bonus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payrollbatchline",
            name="thirteenth_bonus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="payrollbatchline",
            index=models.Index(fields=["date"], name="payroll_pay_date_deb5ff_idx"),
        ),
    ]
