# Generated by Django 5.2.4 on 2025-08-01 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0015_alter_payrollbatchline_extra_hours_qty_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payrollbatchline",
            options={"ordering": ["date", "created_at"]},
        ),
    ]
