# Generated by Django 5.2.4 on 2025-08-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0016_alter_payrollbatchline_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
