# Generated by Django 5.2.4 on 2025-08-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0017_alter_payrollbatch_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollbatch",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
